
Applicant.create(name: "Amanda",	school: "Stanford",	resume_rating: 7)
Applicant.create(name: "Emma",	school: "Harvard",	resume_rating: 7)
Applicant.create(name: "Cindy",	school: "University of Houston",	resume_rating: 8)
Applicant.create(name: "Olivia",	school: "Rice University",	resume_rating: 9)
Applicant.create(name: "Jordan",	school: "Texas A & M", resume_rating: 6)
Applicant.create(name: "Derek",	school: "Massachusettes Institute of Technology",	resume_rating: 8)
Applicant.create(name: "Brandon",	school: "University of Texas - Austin",	resume_rating: 7)
Applicant.create(name: "John",	school: "Carnegie Mellon", resume_rating: 8)
Applicant.create(name: "Carl",	school: "University of Houston", resume_rating: 6)
Applicant.create(name: "Jennifer",	school: "Rice University", resume_rating: 8)
Applicant.create(name: "Jessica",	school: "Flatiron School", resume_rating: 9)
Applicant.create(name: "Mark",	school: "Cy-Springs High School", resume_rating: 3)

Interviewer.create(name: "Thomas",	job_title: "General Manager")
Interviewer.create(name: "Jenny",	job_title: "Solution Architect")
Interviewer.create(name: "Justin",	job_title: "Solution Principal")
Interviewer.create(name: "Alex",	job_title: "Solution Architect")
Interviewer.create(name: "Daniel",	job_title: "Senior Engineer")
